[package]
name = "hermes"
version = "0.1.2"
edition = "2021"

[dependencies]
nom = "8.*"
tokio = { version = "1.45.1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tokio-test = "0.4"
serde_json = "1"
serde_yaml = "0.9"
